---
title: "Energy"
author: "Sondre Løvås"
date: "26 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(zoo)
library(scales)
library(reshape2)
library(ggplot2)
```

```{r data, include=FALSE}
primary_energy_sources <- read.csv("data/primary-energy-consumption-by-source.csv", stringsAsFactors = FALSE)
global_primary_energy <- read.csv("data/global-primary-energy.csv", stringsAsFactors = FALSE)
renewable_energy_investment <- read.csv("data/renewable-energy-investment.csv", stringsAsFactors = FALSE)
```

```{r}
primary_energy_sources
df_primary_energy_sources <- primary_energy_sources %>%
  group_by(Year) %>%
  summarise(sumCoal = sum(Coal.Consumption...EJ))
```

```{r globalEnergySources}
df_global_primary_energy <- melt(global_primary_energy, id.vars = "Year") %>%
  filter(Year >= 1965) %>%
  mutate(variable =
           recode(variable,
                  "Coal..TWh..direct.energy."="Coal",
                  "Oil..TWh..direct.energy."="Oil",
                  "Gas..TWh..direct.energy." = "Gas",
                  "Hydropower..TWh..direct.energy."="Hydropower",
                  "Nuclear..TWh..direct.energy."="Nuclear",
                  "Solar..TWh..direct.energy."="Solar",
                  "Other.renewables..TWh..direct.energy."="Other renewables",
                  "Traditional.biomass..TWh..direct.energy."="Biomass",
                  "Wind..TWh..direct.energy."="Wind",
                  "Biofuels..TWh..direct.energy." = "Biofuels"))

df_global_primary_nonrenew <- df_global_primary_energy %>%
  filter(variable == "Coal" | variable == "Oil" | variable == "Gas")

df_global_primary_renew <- df_global_primary_energy %>%
  filter(variable == "Hydropower" | variable == "Solar" | variable == "nuclear" | 
         variable == "Other renewables" | variable == "Wind")
```

```{r renewableEnergyInvestment}
df_renewable_investment <- renewable_energy_investment %>%
  group_by(Entity) %>%
  rename("Investment"="Investment.in.Renewables.by.Region..IRENA..2016..")
df_renewable_investment
```





This plot shows global consumption of primary energy sources. 
```{r plotGlobalEnergySources, fig.width=14}
ggplot(df_global_primary_energy, aes(Year, value, col=variable)) + 
  labs(y="TWh", title="Global primary energy sources.", colour="Source") +
  geom_line()
```
As expected, coal, oil and gas are the worlds primary energy sources. The next visualization tries to emphasize in a higher degree.

```{r}
ggplot(df_global_primary_energy, aes(Year, value, fill=variable)) + 
  labs(y="TWh", title="Global primary energy sources.", colour="Source") +
  geom_area(position = "stack") 
```


Dividing the renewable sources from the nonrenewable sources, it can bee seen that renewable energy has been on a heavy rise since around 2005. 
```{r plotNonVsRenew, fig.width=14}
plt_renew <- ggplot(df_global_primary_renew, aes(Year, value, col=variable)) + 
  labs(y="TWh", title="comsumption of renewable energy.", colour="Renewable sources") + 
  geom_line()
plt_nonrenew <- ggplot(df_global_primary_nonrenew, aes(Year, value, col=variable)) +
  labs(y="TWh", title="Consumption of nonrenewable energy.", color="Nonrenewable sources") +
  geom_line()
gridExtra::grid.arrange(plt_renew, plt_nonrenew, ncol=2)
```

```{r fig.width=14}
ggplot(df_renewable_investment, aes(x=Year, y=Investment, colour=Entity)) + 
  labs(y="Investment in billion USD.") +
  geom_line()
```

